### ISSUE TITLE
missing common and GUI 

### ISSUE THREAD

**Issue by deveuper** [NGEmu/NGEmu#3]
missing common and GUI documents

**Comment by tambry** [comment]
Common's probably been missing for at least 2 years. I certainly don't have the code for it anymore (could probably be trivially rebuilt though).

This repo nowadays is mostly for collecting documentation and the little code that may be useful (the loader stuff is complicated, so seeing the code may help).

**Comment by deveuper** [comment]
Thanks for your reply.My friends want to develop this emulate on PC/Android,so...Google your repo...
Are u interested to develop this emulator again？


------------------ 原始邮件 ------------------
发件人: "Raul Tambre"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 凌晨3:05
收件人: "NGEmu/NGEmu"<NGEmu@noreply.github.com>;
抄送: "攀攀"<249068538@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NGEmu/NGEmu] missing common and GUI  (#3)




Common's probably been missing for at least 2 years. I certainly don't have the code for it anymore (could probably be trivially rebuilt though).
 
This repo nowadays is mostly for collecting documentation and the little code that may be useful (the loader stuff is complicated, so seeing the code may help).

**Comment by tambry** [comment]
Everything that I said in #1 still applies.
